OLED_ENABLE = yes
OLED_DRIVER = ssd1306
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
WAIT_FOR_USB = yes
NKRO_ENABLE = yes
LTO_ENABLE = yes
AUTO_SHIFT_ENABLE = yes

BOOTMAGIC_ENABLE = no
ENCODER_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
RGBLIGHT_ENABLE = no
COMBO_ENABLE = no
WPM_ENABLE = no
